### ISSUE TITLE
Поиск по коду

### ISSUE THREAD

**Issue by andgam** [pavelmaliavkin/partmart#103]
Каталожный и оригинальные номера, как правило, пишутся с разными знаками препинания. В основном тире и точки, но бывают пробелы, косые и т.д. Мы забиваем коды в базу как придется, зачастую удаляя эти знаки препинания. Пользователи, наоборот, копируют код в каком-то источнике и его вставляют в окно поиска.

Мы не можем стандартизировать хранение кодов в базе и не можем стандартизировать ввод запроса. Потому было бы удобно анализировать только цифры и буквы при поиске опуская все знаки препинания. Это сложно сделать?

Пример:
1. В базе записан код АА-001111
2. Человек 1 ищет АА001111
3. Человек 2 ищет АА    00   111
4. Человек 3 ищет АА.00.111 и т.д.
5. Все находят эту деталь, потому что поиск игнорирует все пробелы и знаки препинания

**Comment by pavelmaliavkin** [comment]
@andgam Тут такое дело, у нас есть только один текстовый поиск, который ищет по Имени и Номеру.
Мне нужно вырезать пробелы и все левые символы из того, что ввел пользователь. Но, тогда не будет работать поиск по двум словам в имени.
Нужно либо как-то научится определять, что ввел пользователь: имя или код. Или сделать 2 разных поиска

**Comment by andgam** [comment]
Все просто - наш дифференцирующий фактор это наличие цифр в запросе (то что вводят в окно поиска). Наименование НИКОГДА не бывает с цифрами, код ВСЕГДА содержит цифры.

То есть, алгоритм такой:
- проверяем есть ли в запросе цифры
- если ДА - выкусываем все пробелы и знаки препинания
- если НЕТ - ищем с пробелами

Код всегда копируют целиком из какого-то справочника = он будет содержать цифры. Даже если кто-то пишет часть кода, то она будет с цифрами. Пример: код MR370776. Напишешь ты "MR" или "MR37" или "MR-37" или "MR 370-77\6" - не важно, так как алгоритм выше будет работать.

Еще вариант - все наименования кириллицей, ВСЕГДА. Все коды могут содержать ТОЛЬКО латиницу. Проверяем на предмет кириллица\латиница и дальше по схеме.

**Comment by andgam** [comment]
Было бы здорово еще показывать в результатах именно тот номер по которому я искал. Как с машинами - их три, но мне показывается та которую я искал. Программа ищет верно, но я как пользователь не понимаю почему мне показывают эту деталь, ведь в соответствующем поле другой код, не тот что я искал.
