### ISSUE TITLE
SEO: url for ajax pages

### ISSUE THREAD

**Issue by pavelmaliavkin** [pavelmaliavkin/partmart#106]
Я заметил, что на сайте страницы обрабатываются аяксом. В справке гугл сказано, что такие 

страницы надо обрабатывать так:

http://partmart.com.ua/category#!disk-tormoznoy

То есть надо добавлять «!» после символа «#» на каждой странице обрабатываемой аяксом. Это 

необходимое условие и оно дает понять поисковикам что это отдельная страница.

**Comment by andgam** [comment]
Не нашел страниц с #. Разве что поиск. Но там нет "!". Так как я не знаю, что такое аякс, будем верить, что задача ОК.
