### ISSUE TITLE
SEO: Generate static pages item names groups (АКПП) and cars brands

### ISSUE THREAD

**Issue by pavelmaliavkin** [pavelmaliavkin/partmart#108]
1. Static url
2. How to handle filter changes? - Hide SEO text and change meta title
3. Manage generic meta title and description - Use standard data for 'search results' page
4. Add posibility to manage meta title and description per page
5. Manage additional text (SEO) per page: h1 (show as part of pager) and detailed text

**Comment by andgam** [comment]
Все ок. Я только не уверен, что мы должны оставаться на той же странице с фиксированным урлом, когда продолжаем поиск по базе. Как то странно выглядит, но механике не вредит.
