### ISSUE TITLE
SEO: Item details page - add altText attribute for product images

### ISSUE THREAD

**Issue by pavelmaliavkin** [pavelmaliavkin/partmart#109]

**Comment by andgam** [comment]
А что ты в этот тэг автоматом пишешь? Нужно писать название детали + марка и модель авто. Желательно на двух языках.

Пример: Генератор Тойота Камри Toyota Camry

**Comment by pavelmaliavkin** [comment]
@andgam Пишу как сказали СЕО ребята - название детали

**Comment by andgam** [comment]
только что переговорил с Сашей - пишем названием детали + марка\модель кириллица + марка\модель латиница. Так как в примере выше.

И было бы здорово насильно прописать этот тэг всем уже существующим фоткам товаров.

**Comment by andgam** [comment]
Я даже сам смог найти этот alt tag в коде :)
