### ISSUE TITLE
SEO: optimize loading speed

### ISSUE THREAD

**Issue by andgam** [pavelmaliavkin/partmart#120]
Саша подкинул сайт, который анализирует скорость загрузки сайта и причины по которым что либо тормозит.

https://developers.google.com/speed/pagespeed/insights/?hl=ru&url=http%3A%2F%2Fpartmart.com.ua%2F&tab=desktop

У нас это в основном тяжелые картинки на главной. Такая задача уже есть в картинках, но все остальное нужно посмотреть.

Опять же, если нужны будут комментарии - можем обратиться к Саше.

**Comment by andgam** [comment]
Давай решим - мы будем на лету обжимать картинки или я руками перед заливкой буду? Какие именно картинки нужно обрабатывать? и т.д.

**Comment by andgam** [comment]
Я добавил большие картинки на главной в разделы интересные предложения - подвисает, долго прорисовывает картинки. Нужно на лету их обжимать до заданных параметров. Размер в пикселях подбери сам (примерно как сейчас). Сам механизм обжимки у нас есть.

**Comment by pavelmaliavkin** [comment]
Что такое обжимать на лету?
Я могу либо их сохранять уже маленькими. Либо сохранять большими, и обжимать до нужных размеров когда они нужны.

**Comment by andgam** [comment]
1. Для тех миниатюр, которые не кликабельны - уменьшаем при загрузке и сохраняем на сервере маленькими. Например - горячие предложения на главной. Вариант 1.

2. Для всех кликабельных миниатюр сохраняем картинку на сервере в большом размере. Этот "большой размер" нам нужно выбрать, чтобы они не были разные и не скакали при просмотре. Пример - картинки в детальной карточек товара, прсмотр фото в результатах поиска, статьи. При этом миниатюры должны ужиматься тоже до "стандартного размера", который мы утвердим. Вариант 2.

**Comment by andgam** [comment]
Прогнал тот же тест на гугле - опять пишет что картинки здоровые
![2](https://cloud.githubusercontent.com/assets/11595408/13422540/2ed39774-df9e-11e5-9f8f-6b2516dca016.png)

И мы с тобой не обсуждали и не утверждали размеры до которых будут обжиматься миниатюры и развернутые картинки. Что и насколько сейчас сайт по факту обжимает?

**Comment by pavelmaliavkin** [comment]
Ты проганял тесты на лайве, а изменения только на бете.
Миниатюры обжимаются до размеров блока, куда она вставляется

**Comment by andgam** [comment]
Протестил тест, вроде все ок :)
