### ISSUE TITLE
Реорганизовать админку

### ISSUE THREAD

**Issue by andgam** [pavelmaliavkin/partmart#124]
Нужно подумать как логично и удобно организовать разделы в админке и блоки внутри разделов.

**Comment by pavelmaliavkin** [comment]
Я бы предложил слева добавить гармошку (типа так: https://splearnings.files.wordpress.com/2015/03/toggle.jpg).
На сейчас допустим: Настройки, контент, пользователи

А там уже можно еще сделать подразделы типа табов.

**Comment by andgam** [comment]
1. Группируем и переименовываем как на картинке
![3](https://cloud.githubusercontent.com/assets/11595408/12871315/9cc86e6e-cd7c-11e5-92c4-53fb0ef8d3f9.png)
2. Гармошку не нужно - лишний клик. Оформи примерно как на скриншоте (серая подсветка, шрифты - все стандартное)
3. Для SEO категории - разбей лист пополам по вертикали и сделай в каждой половине по 2 колонки. Слева "Категории товара", справа "Автомобили". Чтобы вниз много не крутить.
