### ISSUE TITLE
Illegal characters in path

### ISSUE THREAD

**Issue by pavelmaliavkin** [pavelmaliavkin/partmart#125]
некоторыми позициями выскакивает вот такая ошибка (пример - кнопка стеклоподъемника)
![1c7cbec4-ccdf-11e5-911d-b0943f6327db](https://cloud.githubusercontent.com/assets/11453938/12879711/4ac58a7e-ce40-11e5-8848-e2efeceabcf9.png)

**Comment by pavelmaliavkin** [comment]
Проблема была в мягком знаке. Он переводился в кавычку, а такого в урл совать нельзя.

**Comment by andgam** [comment]
Там был твердый знак. Проверь чтобы они оба больше не выстреливали.

**Comment by andgam** [comment]
Не могу проверить, потому что на тесте нет "кнопки стеклоподъемника". Вот и поэтому тоже нам нужно как-то копировать реальную базу сюда.

Пока считаем, что все ОК.

**Comment by andgam** [comment]
Я добавил руками сам новый товар:
1. "стеклоподъемник" он в ссылке записал его как steklopod-emnik. 
2. "моль" система записала как mol

Зачем нам дефис в середине слова? Может проще всегда опускать мягкий и твердый знаки? Например - steklopodemnik.

**Comment by pavelmaliavkin** [comment]
Если вырезать, будет больше вероятность, что 2 слова получат одинаковое значение при трансляции. + гугл понимает, что вместо прочерка должна быть какая-то буква. Он умный, сам умеет трансляцию делать.
