### ISSUE TITLE
Удаление залитых на сервер картинок

### ISSUE THREAD

**Issue by andgam** [pavelmaliavkin/partmart#128]
1. Когда я заливаю картинки на сервер, то они там остаются навечно. Иногда мне нужно их удалять, потому как копится мусор и тяжело в нем ориентироваться. Конкретно, нужна возможность удалять картинки с сервера в статьях и в админке (все что на главной).

2. Если хозяин запчасти удаляет к ней картинку или меняет, то старая автоматом удаляется. На сервере это не храним.

**Comment by pavelmaliavkin** [comment]
Добавил в админку: File manager

**Comment by andgam** [comment]
Сам механизм - ОК. Добавленные фотки тут отображаются. Существующие удаляются.

По мелочам:
1. File manager = Управление файлами
2. Название папок тоже на русском
3. когда я переключаюсь между папками, мне не нужно в них проваливаться и потом жать "назад". Нажатие на папку должно ниже отображать ее содержимое, но само переключение между папками происходит как клик на закладку в браузере. По умолчанию я вижу содержимое первой папки
4. для папок не нужно картинок, иконок и т.д. Просто название папки. Сейчас я вижу это
![1](https://cloud.githubusercontent.com/assets/11595408/13422192/bf6279b6-df9b-11e5-8da9-64f7ea3ef2ee.png)

**Comment by pavelmaliavkin** [comment]
Папки на русском написать не могу, так как они называются на англ.
