### ISSUE TITLE
Дизайн магазина Сервис55

### ISSUE THREAD

**Issue by andgam** [pavelmaliavkin/partmart#131]
1. Все цены округлять до целых грн, без знаков после точки. Сейчас там вообще глюк - иногда показываются 2 иногда 4 цифры после точки.
2. Порядок расположения кодов такой же как на партмарте (и в карточке товара и при добавлении нового). Внутренние переименовать на другие.

![1](https://cloud.githubusercontent.com/assets/11595408/13807085/03c694d4-eb68-11e5-9d2a-b6197186ef08.png)

**Comment by andgam** [comment]
1. Цена в карточке все равно с нулями. В попапе ОК
![2](https://cloud.githubusercontent.com/assets/11595408/13844497/b7c19f62-ec42-11e5-8f1b-2c78227a8afd.png)
2. Номера ОК

**Comment by andgam** [comment]
Если глюк с прыгающими нулями исчез (их иногда до 5 было), то можно не менять. это не принципиально!

**Comment by pavelmaliavkin** [comment]
@andgam Да, я это видел. Но, решил, что это только админов, и так норм. Чтобы они могли видеть округление.
