### ISSUE TITLE
Отправка sms с сайта

### ISSUE THREAD

**Issue by pavelmaliavkin** [pavelmaliavkin/partmart#65]
добавить возможность отправлять смс с партмарта

**Comment by pavelmaliavkin** [comment]
@andgam Почему она на мне в статусе аналайз?

**Comment by andgam** [comment]
Писал комент - он видно не отправился...

ты давал инфу по тому солько стоят эти смски. я потерял ее где-то. Можешь еще раз сюда закинуть? подумаем может быть эта тема решится вместе с темой восстановления паролей

**Comment by pavelmaliavkin** [comment]
@andgam 

Первых 2 сервиса с одинаковой ценой на отправку смс: 0.16 копеек
http://sms-fly.com/Info/Prices/
http://svitsms.com/Info/Prices/

Процесс интеграции практически одинаковый, и достаточно простой.

**Comment by pavelmaliavkin** [comment]
@andgam 
Да, цены поменялись. одна смс в районе 25 копеек

**Comment by andgam** [comment]
делаем. даже 100 смс в мес. это копейки, а у нас пока и того не будет. берем этот сервис https://turbosms.ua/price.html

что подключаем на sms:
1. восстановление пароля (отдельная тема)
2. уведомление админа о запросе на регистрацию
3. уведомление админа об успешном пополнении счета любым пользователем
4. уведомление Владимира Демицкого (основной телефон) о заявке "восстановление на заказ"

**Comment by pavelmaliavkin** [comment]
@andgam 

Привет, 
1. Разбей, пожалуйста, все задачи отдельно. В этой задачи я просто реализую возможность отправлять смс.
2. Перепробовал эти сервисы и несколько других - все гавно. смс приходит в течении 5-10 минут, это очень долго. Проблема в том, что они ориентированы на массовую рассылку - спам.

И того что нашел: http://smsc.ru/tariffs/#tf
Он москольский :), но работает хорошо. смс приходит быстро, проблем с пополнение у меня не возникло. Цена за смс получилась чуть меньше 20 копеек.
Подключать его?

**Comment by pavelmaliavkin** [comment]
@andgam 
Я в тестовом режиме его поклацал - это лучшее что я за сегодня видел. А перепробовал я сегодня штук 10.

Если устраивает - зарегайся и скинь мне логин пароль на почту, так как задачи могут видеть все.

**Comment by andgam** [comment]
1. Задачи разбил. Здесь оставляем только базовый функционал - отправка смс
2. Сервис предложенный тобой - ОК
3. логин и пароль отправил на почту

**Comment by andgam** [comment]
Сами смс ОК, там вопрос по дизайну, но это я отдельно напишу
