### ISSUE TITLE
скачут страницы при обновлении

### ISSUE THREAD

**Issue by andgam** [pavelmaliavkin/partmart#68]
у нас уже были такие\похожие проблемы и мы тогда решили что дело в полосе прокрутки. Решили больше внимания не уделять. Теперь стало сильно раздражать вот что:

1. видны две полосы прокрутки одна из которых неактивна. Она активизируется только при включении попапа, например, добавить товар
![1](https://cloud.githubusercontent.com/assets/11595408/11093134/088b9670-8891-11e5-8de6-975ba6ee1fca.png)
2. нав главной - некоторые элементы прорисовываются чуть позже. например - шестеренки. получается эффект загрузки с дерганьем
3. результаты поиска - загружаются по частям и с дерганиями
- фильтр вид товара загружается на секунду позже всего остального
- фильтр фирма - тоже с задержкой
- происходит дергание страницы влево-вправо на пару пикселей раза 3-4
- потом только загружается вся таблица с данными
4. при переключениями между любыми пунктами меню в админке происходит дергание всей картинки влево-вправо. сайт как бы аджастится и потом становится на место. но любой клик сопровождается "утруской"
5. и т.д.

суть - некоторые элементы загружаются дольше чем другие - шестеренки, сложные фильтры. нужно их как то задерживать и показывать все вместе. Кроме того мешает второй скрол - из-за него вся страница аджастится и трусится при любом обновлении

**Comment by pavelmaliavkin** [comment]
У меня не получаеться сделать 2 полосы прокрутки!

По поводу прыгания и разного времени загрузки. Вообще это норма, когда картинки грузятся дольше. Также прыгать может текст, если он использует специализируемые шрифты (ждет пока шрифты загрузятся). Конкретно у нас прыгают еще и выпадающие-списки.
С этим практически нереально что-то сделать (выпадающие списки это вообще отдельная тема. На каждом проекте где они кастомные - вылазят проблемы).

Как решение в лоб - можно все страницы показывать белыми, а через секунду после загрузки показывать то что есть. Но мое личное мнение - это норма. Локально у меня все отлично, тормозит загрузка данных через интернет.

**Comment by andgam** [comment]
Не понял что значит "не получается сделать 2 полосы прокрутки". Они есть, скрин я показал, их нужно убрать. Отдельно стоит обсудить нужна ли там полоса или колесиком пусть крутят.

Дергание - давай поговорим по телефону.

**Comment by andgam** [comment]
оставляем полностью белую ширму и задержку 100 мс.

со вторым скролом и дерганием связанным со скролом будем рабираться если появится снова
