### ISSUE TITLE
Восстановление пароля пользователем

### ISSUE THREAD

**Issue by pavelmaliavkin** [pavelmaliavkin/partmart#69]
Продумай, как мы будем восстанавливать пароли.
Я вижу такие варианты:
1. Подключить возможность отправки смс и добавить кнопку "сбросить пароль". Отправлять на телефон какой-то код, и если пользователь его ввел обратно на сайт - скидывать ему новый пароль или давать ввести новый.
2. Добавить в админку возможность менять пароль. Тогда пользователи будут звонить админу. + это будет не секьюрно, так как админ будет знать твой пароль. Думаю это не всем понравится.

**Comment by andgam** [comment]
1. делаем 1-ую опцию. Когда пользователь жмет кнопку "восстановить пароль" (там где вход) то ему на номер телефона отправляется временный пароль, который система сгенерила сама. 
2. Пароль простой - 6 рандомных цифр.
3. Система соотвественно скидывает пароль и ставит тот который в смс отправлен
4. Если номер не указан - выскакивает попап (стандартный) с надисью "Укажите, пожалуйста, номер телефона, который был использован при регистрации и затем нажмите кнопку "Восстановить пароль".
5. Если номер укзан и смс отправлено - выскакивает попап (стандартный) с надписью "На Ваш номер телефона был отправлен временный пароль. Вы можете сменить пароль в Кабинете, в разделе "Личные данные".
6. Если такого номер нет вообще в базе - попап "В нашей базе нет аккаунта с указанным номером телефона. Пожалуйста, проверьте номер и попробуйте еще раз."

**Comment by andgam** [comment]
Смс пришла мгновенно, но под этим паролем я не смог зайти - неверный пароль.

**Comment by pavelmaliavkin** [comment]
@andgam 
А под старым можешь зайти?

**Comment by andgam** [comment]
виноват, это я ошибся - забыл активировать пользователя :) Все ок, только здесь как и везде - убери в смс лишние пробелы около скобок.

**Comment by andgam** [comment]
Все ок, сделаем просто отдельной задачей - чтобы сообщения приходили от partmart.com.ua
