### ISSUE TITLE
Админ видит устаревшие записи

### ISSUE THREAD

**Issue by andgam** [pavelmaliavkin/partmart#76]
Под админом я могу видеть застаревшие карточки, которые вероятно были удалены. Я вижу левые записи на главной в перечне номенклатуры, я вижу их в результатах поиска. Нужно почистить.

1. Как админ я вижу вот что (100% устаревшее)
![1](https://cloud.githubusercontent.com/assets/11595408/11239877/4e53bb68-8df7-11e5-82dc-cc026de36ffe.png)

2. При клике открывается такой товар и его карточка
![2](https://cloud.githubusercontent.com/assets/11595408/11239886/6001cd96-8df7-11e5-8a9d-8978fe5785bb.png)

3. при входе под хозяином детали - ничего такого нет. Ни в кабинете, ни на главной, ни в результатах поиска.
![3](https://cloud.githubusercontent.com/assets/11595408/11239944/a4fb896e-8df7-11e5-9e1c-3794a2b8db9a.png)

**Comment by pavelmaliavkin** [comment]
Нашел проблему. 
Дело в том, что сам продавец не видел запчасти с 0 ценой и без имени. Теперь будет видеть.

**Comment by andgam** [comment]
И как это решает проблему - он будет видеть и сможет исправить?

Но тогда второй вопрос - почему я в кабинете эти детали не вижу? Там даже с нулем все моё мне должно быть видно.

**Comment by pavelmaliavkin** [comment]
Да, продавец их будет видеть и сможет исправить.

Ты их не видел как продавец из-за проблемы.

**Comment by andgam** [comment]
1. Я как админ продолжаю видеть детали с нулевой стоимостью
![1](https://cloud.githubusercontent.com/assets/11595408/11456316/38ee9dde-968e-11e5-997a-9aafa8ae404e.png)

2. Но когда я захожу под сервисом, то не вижу этих деталей по прежнему
![2](https://cloud.githubusercontent.com/assets/11595408/11456317/483fcb8c-968e-11e5-921c-11fe02df061f.png)

Продавец должен видеть свои детали с нулевой ценой или неактивные (снятый глаз). Другой вопрос что обе эти группы не должны видеть посторонние (это все кроме самого продавца и админа).

**Comment by pavelmaliavkin** [comment]
Я этого ожидал. Решил не тратить на это время.
1. Покупатель "плохие" запчасти не видит!
2. Админ видит все и везде
3. Продавец может видеть свои "плохие" запчасти только в складе. В других местах он с ними всеравно ничего не сделает. + Если он не видит запчасти на главное, сразу пойдет на склад проверять.

**Comment by andgam** [comment]
1. Вот я вижу как админ эту запчасть и вижу что она на Демицком
![2](https://cloud.githubusercontent.com/assets/11595408/11467556/9e39ce8e-9751-11e5-8ca3-d0672bf659fe.png)

2. Вот Демицкий зашел в свой кабинет - и там он ничего не видит! 
![3](https://cloud.githubusercontent.com/assets/11595408/11467572/b3452846-9751-11e5-9c9e-681f654c29e4.png)

3. Поиск не работает. Я еле нашел глазами!
![3](https://cloud.githubusercontent.com/assets/11595408/11467697/7e46b280-9752-11e5-9937-829022682267.png)

Соответственно проблема остается - Демицкий не видит глючных записей на главной, не видит их в поиске и не может найти ее среди множества своих деталей глазами. Он просто не знает о проблеме. 

Сюда же второй момент - почему продавец может включить глаз когда карточка не полная? Но это решим отдельной задачей :)

**Comment by andgam** [comment]
Слушай, а что ты мы тут по сути будем менять? Сейчас и админ и владелец детали имеют возможность все изменить. Посторонние пользователи этого все равно не видят...

Может так и оставить? А порешаем лучше проблему нулевой цены, неполных карточек и отображения товара?

**Comment by pavelmaliavkin** [comment]
@andgam Прилизительно это я и имел ввиду.
Порешаем те проблемы, а потом, если будет нужно, будем решать новые. Эту можно закрывать.
Тоесть, эта задача была - владелец должен видеть ВСЕ свои запчасти в кабинете

**Comment by andgam** [comment]
Согласен. Закрываем. Я руками как админ за всех подправлю пока названия.
