### ISSUE TITLE
Не удаляются записи в справочнике

### ISSUE THREAD

**Issue by andgam** [pavelmaliavkin/partmart#77]
1. Редактирую справочник в последней версии хрома, 18.11.15 около 18:15. Вот что делаю
![2](https://cloud.githubusercontent.com/assets/11595408/11246688/56108bcc-8e21-11e5-8d72-3e6dfebcf5ec.png)

2. Вот что вижу в результате, после нажатия удалить
![1](https://cloud.githubusercontent.com/assets/11595408/11246693/5fa691e0-8e21-11e5-8cbe-d746c5e448bd.png)

3. Проверяю существование записей ссылающихся на "раздатку" - их нет
![3](https://cloud.githubusercontent.com/assets/11595408/11246709/725075cc-8e21-11e5-9474-c527405b6d23.png)

Вполне возможно, что у тебя она удалится с первого раза. Но почему у меня не удаляется?

**Comment by pavelmaliavkin** [comment]
@andgam 
Я понял.
Смог воспроизвести в следующем сценарии:
1. Удаляем все дочерние ноды
2. Пробуем удалить эту ноду.

Проблема в том, что когда сервер отдал тебе информацию про каталог - родительскую ноду действительно нельзя было удалять.

Достаточно простых решения 2:
1. После каждой операции запрашивать данные с сервера. Проблема будет в том, что все снова будет свернуто и будет неудобно работать.
2. Убрать проверку на клиенте и тебе будет выдаваться ошибка, если на ней есть запчасти. Нужно проверить на лайве что это работает. Если решишь делать так - создай новую спецификацию и запчасть к ней и попробуй удалить.

Из посложнее: отслеживать это на клиенте.

**Comment by andgam** [comment]
убираем проверку на клиенте
