### ISSUE TITLE
Нормальный e-mail

### ISSUE THREAD

**Issue by andgam** [pavelmaliavkin/partmart#79]
Сейчас уведомления приходят с autoparts.info@gmail.com - что не очень серьезно. Мы теоретически можем настроить свою почту, что-то вроде admin@partmart.com.ua или info@partmart.com.ua? 

Это нужно только для автоматических рассылок уведомлений. Полноценная почта для корреспонденции (типа гмейл) не нужна. Мы будем по прежнему работать с входящими сообщениями через админку, а писать никому не будем (только звонки).

**Comment by pavelmaliavkin** [comment]
@andgam Почта будет слаться с admin@partmart.com.ua.
Почта которую кто-то пришлет на admin@partmart.com.ua - будет пересылаться тебе

**Comment by pavelmaliavkin** [comment]
@andgam 
Можешь переслать письмо?

**Comment by andgam** [comment]
1. поменяй адрес для пересылки входящих писем с andrey.gamolya@gmail.com на andgam@mail.ru 

2. Проверь чтобы все входящие письма дублировались в ящик на партмарте в админке

**Comment by andgam** [comment]
все ок, но когда кто-то пишет на admin@partmart.com.ua мне в ящик письма доходят (на мейл.ру) а в ящик админа на партмарте не доходят. нужно это будет решить отдельной задачей, наверно.
