### ISSUE TITLE
Доработка горячих предложений

### ISSUE THREAD

**Issue by andgam** [pavelmaliavkin/partmart#83]
1. Админка - настройки домашней - делаем 10 полей под БУ запчасти и 10 под восстановленные. Аналогично существующим.
2. Под чек-боксом "показывать" делаем чек-бокс "Включить рандом". Если галочки нет - на главной отображаются первые 4 детали из списка. Если есть - отображаются произвольные 4 детали из списка. При этом не может быть 2 одинаковые детали в одном наборе и при каждой перезагрузке страницы набор обновляется. Естественно БУ отдельно, восстановленные отдельно.

**Comment by andgam** [comment]
поля - ок, рандом ок. но есть глюк - отображается то 1 предложение, то 2, а должно быть всегда 4. Это при том что все 10 полей заполнены. Пробовал обновляться раз 10.

Кстати рандом должен выбирать только из заполненных полей, пустые он не выводит!

**Comment by pavelmaliavkin** [comment]
@andgam Он пустые не выводит.
Такой глюк может быть если ты вбил что-то в поле, но запчасти с таким ИД нету (или она не доступна обычным пользователям).
