### ISSUE TITLE
Новый раздел: вопросы-ответы

### ISSUE THREAD

**Issue by andgam** [pavelmaliavkin/partmart#86]
Я буду заниматься вопросами-ответами. Нужен пункт меню, удобный просмотр и навигация, архив вопросов и т.д.

1. Делаем пункт в меню "Вопросы-ответы". При клике - новая страница, стиль оформления стандартный. Виден перечень всех вопросов с заголовками, именем автора, датой. Давай попробуем таблицу с стандартными заголовками и оформлением. Внизу переключение между страницами и "показывать по". Если сложно представить - я попробую нарисовать. Пока макета нет.

2. Добавляем кнопку перехода к разделу "Вопросы ответы" на главной, как на образце
![4](https://cloud.githubusercontent.com/assets/11595408/11457320/81a46ebc-96ae-11e5-9439-f30444b869fc.png)

3. Делаем сортировку по автору, по дате - сверху синяя надпись над таблицей, как на образце
![5](https://cloud.githubusercontent.com/assets/11595408/11457328/b10199f0-96ae-11e5-87d8-450f72dc7300.png)

4.  Нужен где то поиск по ключевым словам. Прининцип - как в таблице результатов поиска. Очевидно, тоже в заголовке таблицы.

**Comment by andgam** [comment]
1. Добавить соотвествующий пункт в меню. Сейчас его нет.

2. Заголовок вопроса стандартным серым цветом. В конце строки кнопка "подробней" (синяя с подчеркиванием, как на главной)

3. Если в результате поиска ничего не обнаружено - нужно выдать соответсвующее собщение. У нас уже есть такое в кабинете

4. когда провалился в вопрос, то кнопка - Перейти в раздел "вопросы-ответы" снизу и синяя

6. Заголовки "Вопрос" и "Ответ" (когда провалился в вопрос) - стадартные

7. Заголовок = Тема

**Comment by andgam** [comment]
Отдельно, давай подумаем. А что если мы каждый вопрос\ответ будем открывать не в новом окне, а в том же списке при клике он будет просто разворачиваться. Второй клик - сворачиваться. Тогда у нас не будет прямой ссылки и может хуже будет для SEO, но будет удобно и красиво.

Может ты знаешь как технически возле каждого вопроса поставить "зачечку\закладку", чтобы можно было на него давать "прямую ссылку" по которой открывается станица вопросы-ответы в нужном месте и именно этот вопрос уже развернут?

**Comment by pavelmaliavkin** [comment]
@andgam 
Все зависит от вопросов и ответов. Если они будут достаточно большие, и у нас будет больше 10 вопросов - будет каша.

**Comment by andgam** [comment]
Вопросов будет около 10 в день, в месяц пусть 200. Грубо - за год наберем пару тысяч. Если мы отображаем по 50 заголовков на странице (в одну строку) то это 40+ страниц. И так далее...

Сам вопрос обычно 1-2 предложениями. Ответ 4-5 предложений. Без комментариев и последующей переписки. Учитывая наш стандартный шрифт это всего 4-5 строк вместе с заголовками "вопрос" и "ответ".

Это точно будет удобно и читабельно. Вопрос в том можем ли мы как то помечать эти зоны (где находится нужный вопрос и ответ) и давать прямую ссылку? можем ли мы разворачивать сразу нужный ответ, если пользователь перешел по прямой ссылке с главной или извне?

**Comment by andgam** [comment]
1. ок
2. "подробней" сразу после текста, а не в конце ячейки. Поле "автор" шире за счет темы.
3. ок. 
4. кнопка по левому краю и сразу под текстом + стандартный отступ, а не внизу страницы
5. ок
6. ок
7. Сортировка по дате и по автору - в одном ряду с поиском, над соответствующими колонками в таблице.

оформление в виде разворачивающегося списка будет как отдельная задача.

**Comment by pavelmaliavkin** [comment]
@andgam попровил все кроме сортировки. Я думаю это будет убожество.
Подумай глобально насчет сортировки в таблицах. Обычно для сортировки используют сам заголовок таблицы + рядом иконку - http://blog.bcdsoftware.com/wp-content/uploads/2012/11/sortable-columns4.png

Подумай, и создай задачу, у нас есть несколько таких мест.

**Comment by andgam** [comment]
согласен. порешаем отдельно.
