### ISSUE TITLE
Корректировки по SMS

### ISSUE THREAD

**Issue by andgam** [pavelmaliavkin/partmart#89]
1. В смсках от партмарт некрасиво отображается номер. Много скобочек и пробелов, тяжело читается. Давай без скобок и пробелов вообще. И все отделяем запятой. Баксы в скобках. Пример - Пополнение: Владимир Демицкий, +380632876413, 10 грн. (0.39$). Такой же принцип во всех сообщениях.

2. Сейчас все СМС приходят от "Partmart". Давай сделаем от "partmart.com.ua". Жирным но с маленькой.

3. Нужно отправлять еще смс при успешной активации - то есть когда я глаз включил первый раз для нового пользователя. Содержание - Ваш аккаунт на partmart.com.ua успешно активирован! В админке еще одна запись с чек-боксом - Отправлять SMS при первой активации нового пользователя на его номер.

**Comment by pavelmaliavkin** [comment]
@andgam 
2. Не могу. Там ограничения: "до 11 букв". Можешь сам поменять: http://smsc.ru/senders/edit/?id=119019

**Comment by andgam** [comment]
ок, принято.
