### ISSUE TITLE
Обязательные поля в карточке товара

### ISSUE THREAD

**Issue by andgam** [pavelmaliavkin/partmart#92]
1. Давай пометим звездочками обязательные поля в карточке товара. Причем и в новой и в редактируемой карточке.
![2](https://cloud.githubusercontent.com/assets/11595408/11494260/73105760-9809-11e5-89fb-7d103f0a7c1d.png)

2. Делаем сервисное сообщение (красная полоска сверху) при неполном заполнении - Заполнены не все обязательные поля! Отображение карточки в общей базе невозможно!
При это сохранить карточку и редактировать через кабинет можно.

**Comment by pavelmaliavkin** [comment]
@andgam 
Для сохранения целостности базы, я настоятельно рекомендую запретить создавать "битые" товары. Подумай.

**Comment by andgam** [comment]
Согласен с тобой - нам недоделанный и полумертвые карточки не нужны. Потому заполнять нужно все обязательные поля сразу при создании карточки. Тем более что все эти данные известны сразу. В том числе цена должны быть указана сразу. 

Но можно сохранять кол-во ноль. Это логично, так как товар можно продать, но скоро ожидается еще один такой же. Плюс, если каких-то данных пока не хватает (код, фотка) то можно пока товар не высвечивать за счет того что поставлено кол-во ноль. Ну и само собой тогда глаз не может быть подсвеченым.

Завтра все равно обсудим, чтобы не передергивать.

**Comment by andgam** [comment]
Нужно решать эту задачу в комплекс с №91.

Если согласен с решением описанным в предыдущем комменте - реализовывай. Если нет - давай тогда обсудим.

**Comment by andgam** [comment]
Сохранение возможно только при заполнении обязательных полей. Обязательные поля: Тип, Наименование, Деталь, Машина.

Активация возможна при заоплнении всех обязательных полей + цена > 0 и количество >0
