### ISSUE TITLE
Новые роли

### ISSUE THREAD

**Issue by andgam** [pavelmaliavkin/partmart#93]
Я часто приглашаю людей посмотреть и прокомментировать базу. Им нужно посмотреть на кабинет и админку, чтобы дать отзыв. Иногда нужно поклацать, создать\отредактировать деталь, пополнить счет.

Сейчас я либо даю свой пароль тем кому доверяю, либо люди регистрируются. То есть я либо сливаю админский пароль, либо пложу мертвые тестовые аккаунты.

Что мы можем сделать в плане новых ролей (тестер админ и тестер юзер) малой кровью? Можешь дать оценку на сколько это сложно? Грубо говоря - тестовый пользователь все видит, все нажимает, но эффекта на базу это не имеет. Изменения не записываются и не сохраняются, все что он добавил в кабинет удаляется после лог-оффа.

**Comment by andgam** [comment]
Потенциально есть еще одна роль (если наймем человека) - контент-менеджер. Он должен выкладывать\редактировать вопросы и ответы, обновлять фотки на главной, выкладывать\редактировать статьи, заполнять инфо о производителях и т.д.

**Comment by pavelmaliavkin** [comment]
@andgam Как всегда есть несколько вариантов.
1. Быстро и просто
Можно наворотить что-то простое. Это займет порядка 1-2 дней.
Плюсы: достаточно быстро
Минусы: Будет много зашитих правил, и добавление новых ролей будет очень затруднительно. Добавление любой фичи будет требовать прописывания правил для всех ролей.
Уже сейчас, часто возникают проблемы с настройкой доступа для продавца и супер-юзера.

2. Хорошо
Можно сделать более качественно. Ввести понятие ролей, вынести настройку возможностей в админку.
Плюсы: качественно, легко расширяемо, многие вещи ты сможешь сам настраивать в админке.
Минусы: даже с минимальным набором этой займет порядка недели.

подумай.

**Comment by andgam** [comment]
Я склоняюсь ко второму варианту, но не сейчас, а попозже. Нужно чтобы началась движуха на сайте и все это заимело какой-то прикладной смысл. Пока обхожусь временным паролем, который ты потом удаляешь.

Расскажи про "супер-юзера". Это админ? и в чем там проблема\сложность с настройкой?

**Comment by pavelmaliavkin** [comment]
Сложность в том, что везде где у меня разные возможности у простого пользователя и админа, сейчас написано что-то типа:
Если АДМИН ТО ОПЕРАЦИЯ1
Если пользователь ТО ОПЕРАЦИЯ2.

Это я утрирую, но таких мест уже много, а если добавить к каждому такому месту еще одну проверку на тип пользователя, то будет жопа. А ты уже хочешь 2 дополнительный роли.

**Comment by andgam** [comment]
Все понятно. Тогда точно вариант 2. Просто делать его будем тогда когда наймем человека и ему нужен будет такой вот доступ. А мы его пол года уже ищем :)

У тебя кстати никого из знакомых студентов нет? Работа на 2-3 часа в день, обрабатывать картинки, общаться на форумах, редактировать записи на партмарте. Нужно немного понимать в запчастях.

**Comment by pavelmaliavkin** [comment]
Знакомые то есть, но из тех кто хорошо бы (ответственно) занимался такой работой, никто не шарит ничего в авто совсем.

**Comment by andgam** [comment]
Начинаем прорабатывать вариант 2, потихоньку, но добротно.

Роли такие:
1. Админы - я и ты. Можем все
2. Продавец - все кто регистрируется и активированы админом. Могут тоже, что и сейчас
3. Контент менеджер - аккаунт создаешь ты вручную. Видит часть админки (вопросы-ответы, статьи). Потом будет больше
4. Тестер админ - аккаунт создаешь ты вручную. Видит тоже что и админ, но ничего менять не может. Точнее все изменения не сохраняются после выхода и не отображаются в реальной базе. Он чтото тыкает, чтото происходит, но эффекта не имеет и не сохраняется.
5. Тестер продавец - аккаунт создаешь ты вручную. Тот же принцип, но только с кабинетом.

Что нужно:
1. Всеми аккаунтами мы управляем в разделе "пользователи"
2. Любого (кроме админа) можно отключить
3. Легко определить кому что можно, кому чего нельзя
4. Легко добавить новую роль используя разные уровни допуска из пункта 3
5. Подумать на счет слежения за пользотвателями. что именно отслеживать? сложно ли это?

**Comment by andgam** [comment]
Дополнение:
- Админ не может менять некоторые url, не может менять детали в карточках товара. Только админ редактирует все, что связано с SEO.
- Контент-менеджер редактирует и выкладывает статьи и картинки к ним, вопросы-ответы, раздел "производители в меню", картинки в горячих предложениях на главной.
- Гость - незарегистрированный пользователь, может тоже, что и сейчас. В админке управление гостем не нужно.

**Comment by pavelmaliavkin** [comment]
Реализация:
По умолчанию доступ к администрированию имеют только админы.
А админке добавлен раздел: Роли.

Там ты можешь создать новую роль и добавить людей, у которых будет эта роль.
Для каждой роли, ты можешь определить, какие операции может делать человек с этой ролью. Например, ты можешь создать роль SEO, и разрешить им доступ только к разделу SEO. Тогда у этих людей появится доступ в админку, но там будет только раздел: SEO.

Если у человека несколько ролей, и хотябы одна из ролей позволяет ему совершить какую-то опреацию, то человек может совершить эту операцию.

Сейчас там базовые операции. Но, самое главное механизм. В случае необходимости, создавай новую задачу и мы допилим роли.


!!! Сейчас это сделано на отдельной ветке. Если все ок - я залью это на основную ветку. Если нет, тогда буду откатывать бету.

**Comment by andgam** [comment]
1. Когда я захожу под логином админа, то в шапке я вижу и Администрирование и Кабинет и Выход. Такого не должно быть. Если я Админ то я вижу Админку, если я продавец, то я вижу Кабинет. Одновременно я не могу видеть и то и то.
2. Я сейчас могу одному аккаунту присвоить 2 роли - это неправильно. Если я кого-то назначил Админом то он уже не может быть продавцом. Если контент-менеджером, то он не может быть админом. Короче - можно присвоить только 1 роль. Хочешь другую - сними старую роль.
3. Я не могу удалить роли. Вот случайно создал 2 контент-менеджеров. Нужна кнопка "удалить" для роли.
4. В разделе "пользователи" переименовываем заголовок пользователи на "Продавцы". Когда в  разделе "Роли" создается новая роль, то в разделе "Пользователи" появляется новая табличка с одноименным заголовком. Вид таблички такой же как "продавцы", с глазом.
5. Мне нужно создать тестовый доступ - видно все, нажимать можно все, но изменения не сохраняются и не влияют на работу реальной базы. При этом визуально можно все поклацать и посмотреть как работает. Скорей всего нам нужны для каждой роли галочки "может смотреть" или "может редактировать", для каждой строки.
6. Давай разделим права доступа для SEO general и SEO categories
7. Заголовки в таблице "Роли" переводим на русский

Что у нас с настройками по умолчанию? Например, что могут делать все продавцы после регистрации по умолчанию? Эту роль нужно создавать или она генерируется автоматически?

Что у нас с кодом, который отвечает за роли и который я не вижу? Там теперь легко проводить все настройки и изменения, распределять права доступа?

**Comment by pavelmaliavkin** [comment]
1. Я не понимаю, почему тебе это не нравится? Я в принципе не понимаю, почему админ не может добавлять детали? Зачем эти дополнительные ограничения для тебя одного?
Помоему логично, администрировать в админке, и управлять "собой" и своими запчастями в кабинете.

2. Я думаю, что это неправильно. Это не работает. В чем проблема, если один из твоих контент-менеджеров в тоже время является СЕО? Тогда проще вообще ограничивать права для каждого пользователя отдельно?

3. Согласен - сделаю.

4. Сделаю.

5. Тестовый доступ, это совсем другая тема.
Во первых, зачем ты кому-то показываешь как работает админка?
А если это тестовый продавец - может таки вернем функциональность по удалению пользователей? И ты его просто будешь удалять + все запчасти будут сами удаляться?
Обычно подобные проблемы решаются статьями с описанием работы сайта + видео.

6. ок

7. ок


_Что у нас с настройками по умолчанию? Например, что могут делать все продавцы после регистрации по умолчанию? Эту роль нужно создавать или она генерируется автоматически?_
Абсолютно все пользователи являются продавцами. Добавлять детали могут все. Просто ты дополнительно можешь дать больше полномочий своим людям.
Как вариант можно убрать возможность использовать кабинет, если ты хотябы в одной роли.

_Что у нас с кодом, который отвечает за роли и который я не вижу? Там теперь легко проводить все настройки и изменения, распределять права доступа?_
Я честно говоря не особо понял вопрос.

**Comment by andgam** [comment]
1. Есть разные админы. Я и ты - вроде как боги - можем все. Остальные псевдо-админы имеют доступ только к части функционала. Например, контент-менеджер может публиковать статьи из админки и, естественно, ему видна кнопка "Администрирование". Но не тот не тот не может добавлять детали. Я вот не знаю какие детали и как можно добавлять, это знает только оператор Сервиса55 (работник склада), ну и по аналогии любой независимый продавец. Больше того, склад любого продавца это его святыня, туда никто не должен лазить. Потому все кто имеет хоть частичный доступ к администрированию видят только Админку, все продавцы видят только Кабнет. Можем обсудить по телефону.

2. Давай обсудим, может я чего-то не понимаю

5. Тоже много писать, давай обсудим. Ответ на вопрос "Зачем" - я консультируюсь со многими людьми которые мне говорят, что можно улучшить и я когда нанимаю людей показываю им как работает сайт и когда приходят кто-то вроде SEO-шников я показываю им сайт. Хотелось бы один раз для таких целей настроить тестовый доступ, а не давать реальный пароль.

 Думаю есть смысл поговорить по тел или скайпу, за 10 минут закроем все вопросы.

**Comment by pavelmaliavkin** [comment]
1. Можно назначать на несколько ролей
2. Если у человека есть хотя бы одна роль - у него нет доступа в кабинет
3. Тестовый доступ будет даваться к бете

**Comment by andgam** [comment]
Не работают 2 роли одновременно. Я Демицкого назначил на 2 роли - контент и SEO и потом залогинился под ним...

Вот что он видит (только SEO)
![2](https://cloud.githubusercontent.com/assets/11595408/12828036/29f5fa8e-cb8b-11e5-933f-c5bacb9fb070.png)

Я как админ вижу, что он только в одной роли
![3](https://cloud.githubusercontent.com/assets/11595408/12828047/3c695a58-cb8b-11e5-9f9a-9f83b9c51ba3.png)

При проверке оказалось, что когда я присваиваю Демицкому новую роль, его старая автоматом снимается. А мы вроде утвердили возможность назначать несколько ролей

И когда я нажимаю "сохранить" в режиме настройки ролей, меня должно автоматом выкидывать в раздел "Роли".

**Comment by andgam** [comment]
Не принципиально, но после нажатия кнопки "сохранить" я выхожу в раздел "роли" только когда определяю пользователей. Тоже самое нужно, когда я определяю "возможности".
